import Assets from './data/assets';
import { getSkills } from './skills.params';
import { ContractType, type Experience } from './types';

const MY_EXPERIENCES: Array<Experience> = [
	{
		slug: 'IT Technician',
		company: 'University of Agder',
		description: 'Responding to client’s requests and assisting client with general desktop, software and network support. Managing and troubleshooting equipment to ensure that they are running optimally.',
		contract: ContractType.PartTime,
		type: 'PartTime',
		location: 'Grimstad',
		period: { from: new Date() },
		skills: getSkills('svelte', 'ts', 'sass', 'css', 'html', 'js'),
		name: 'IT Technician',
		color: 'darkolivegreen',
		links: [],
		logo: Assets.Unknown,
		shortDescription: ''
	},
	{
		slug: 'Internship',
		company: 'Mechatronics Innovation Lab',
		description: 'Using machine learning algorithms to solve problems that arise while 3D-printing of cement.',
		contract: ContractType.Internship,
		type: 'Internship',
		location: 'Grimstad',
		period: { from: new Date(2023, 8, 15), to: new Date(2023, 12, 20)},
		skills: getSkills('', ''),
		name: 'Internship',
		color: 'gold',
		links: [],
		logo: Assets.Unknown,
		shortDescription: ''
	},
	{
		slug: 'Lab assistant',
		company: 'University of Agder',
		description: 'Assisting the professor in projects. Maintainence of lab equipment.',
		contract: ContractType.PartTime,
		type: 'PartTime',
		location: 'Grimstad',
		period: { from: new Date(2022, 0, 1), to: new Date() },
		skills: getSkills('css', 'html', 'js'),
		name: 'Lab assistant',
		color: 'blueviolet',
		links: [],
		logo: Assets.Unknown,
		shortDescription: ''
	},
	{
		slug: 'Dance Instructor',
		company: 'Kom og Dans',
		description: 'Teaching swing dancing for students from beginner to advanced levels.',
		contract: ContractType.PartTime,
		type: 'PartTime',
		location: 'Grimstad',
		period: { from: new Date() },
		skills: getSkills('svelte', 'ts', 'sass', 'css', 'html', 'js'),
		name: 'Dance Instructor',
		color: 'darkgoldenrod',
		links: [],
		logo: Assets.Unknown,
		shortDescription: ''
	},
	{
		slug: 'Student Housing Host',
		company: 'Studentsamskipnad I agder',
		description: 'Create a social and pleasant environment for everyone who lives at the student housing. Inform new residents about the social community and how things work in the building.',
		contract: ContractType.PartTime,
		type: 'PartTime',
		location: 'Grimstad',
		period: { from: new Date() },
		skills: getSkills('svelte', 'ts', 'sass', 'css', 'html', 'js'),
		name: 'Student Housing Host',
		color: 'aquamarine',
		links: [],
		logo: Assets.Unknown,
		shortDescription: ''
	},
	/**=================== Volunteer Experience ==================**/
	{
		slug: 'Admin & Boat Maintainance',
		company: 'Redcross Hjelpekorps',
		description: 'Create a social and pleasant environment for everyone who lives at the student housing. Inform new residents about the social community and how things work in the building.',
		contract: ContractType.Volunteer,
		type: 'Volunteer',
		location: 'Grimstad',
		period: { from: new Date() },
		skills: getSkills('svelte', 'ts', 'sass', 'css', 'html', 'js'),
		name: 'Admin & Boat Maintainance',
		color: 'aquamarine',
		links: [],
		logo: Assets.Unknown,
		shortDescription: ''
	},
	{
		slug: 'Treasurer & Vice campus Manager',
		company: 'Erasmus Student Network',
		description: 'Create a social and pleasant environment for everyone who lives at the student housing. Inform new residents about the social community and how things work in the building.',
		contract: ContractType.Volunteer,
		type: 'Volunteer',
		location: 'Grimstad',
		period: { from: new Date() },
		skills: getSkills('svelte', 'ts', 'sass', 'css', 'html', 'js'),
		name: 'Treasurer & Vice campus Manager',
		color: 'aquamarine',
		links: [],
		logo: Assets.Unknown,
		shortDescription: ''
	},
	{
		slug: 'Administrator',
		company: 'Ungswingsør',
		description: 'Create a social and pleasant environment for everyone who lives at the student housing. Inform new residents about the social community and how things work in the building.',
		contract: ContractType.Volunteer,
		type: 'Volunteer',
		location: 'Grimstad',
		period: { from: new Date() },
		skills: getSkills('svelte', 'ts', 'sass', 'css', 'html', 'js'),
		name: 'Administrator',
		color: 'aquamarine',
		links: [],
		logo: Assets.Unknown,
		shortDescription: ''
	},
	{
		slug: 'Leader',
		company: 'Fjell og Fjære',
		description: 'Create a social and pleasant environment for everyone who lives at the student housing. Inform new residents about the social community and how things work in the building.',
		contract: ContractType.Volunteer,
		type: 'Volunteer',
		location: 'Grimstad',
		period: { from: new Date() },
		skills: getSkills('svelte', 'ts', 'sass', 'css', 'html', 'js'),
		name: 'Leader',
		color: 'aquamarine',
		links: [],
		logo: Assets.Unknown,
		shortDescription: 'Leader of Fjell og Fjære.'
	},
];

export default MY_EXPERIENCES;
